### PR TITLE
Update abbrs.xlsx

### PR DESCRIPTION
**Pull request by Ephellon**
Updated bullets to be USAF (2022Q4) approved. Also included formatting and sorting.

### CODE REVIEW

**Comment by Ephellon** [comment]
`flight plan flt → pln` (row `29`) is incorrect, it should be `flight plan → flt pln` →

image

**Comment by Matthewenderle** [comment]
@Ephellon The problem with the current layout is if this is approved it will be used for all users, including those not under AFGSC. It would be beneficial if @ckhordiasma was able to make the `Load Common Abbrvs` a drop-down list that had multiple.

I also have a feeling that @ckhordiasma didn't add the complete abbreviations list as he would not want to have people assume it is always correct.

**Comment by Ephellon** [comment]
Okay, I can redo it for [the new bullet list](https://www.angtec.ang.af.mil/Portals/10/Courses%20resources/HQ%20AU%20Writing%20Style%20Guide%20(Feb%202022).pdf?ver=ZHcG5KvfTorFmk2irtnh3A%3D%3D) (uniform across all MAJCOMs)

**Comment by ckhordiasma** [comment]
@Matthewenderle I agree, don't want the default to be a Majcom specific one but maybe a drop-down would be good, will look into that. @Ephellon I can add the one you linked too as the one from Air University

**Comment by ckhordiasma** [comment]
Closing this older PR. Would maybe consider having a dropdown for MAJCOM specific abbreviations or something.

**Pull request closed without merging**
